[build]
target = "avr-none"
    rustflags = ["-C", "target-cpu=atmega328p"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude"

[unstable]
build-std = ["core"]
panic="abort"

[alias]
test-host = "test --target x86_64-unknown-linux-gnu"
